### ISSUE TITLE
The converter is unable to handle whitespace between tags

### ISSUE THREAD

**Issue by marmoure** [evolvedbinary/lwdita#129]
The Saxes parser is parsing whitespace between tags as text nodes.
This will results in the converter trying to place those text nodes as children which  results in invalid tree eg:
```
Failed to convert: non-accepted-child: "text" node can't be a child of "document" node
    at DocumentNode.add 
```

Input XML:
```
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">
<topic>
<title>Some title</title>
  <body>
    <p>asdf</p>
  </body>
</topic>
```

**Comment by marmoure** [comment]
@adamretter This can be fixed by introducing a pre processing function that strips off all the whitespace between the xml tags eg:
```
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">
<topic>
<title>Some title</title>
  <body>
    <p>asdf</p>
  </body>
</topic>
``` 
This will be refactored into
```
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd"><topic><title>Some title</title><body><p>asdf</p></body></topic>
```

PS: We did look into [the parser option](https://www.npmjs.com/package/saxes) and we didn't find any option that disables treating whitespace between tags as text nodes.

**Comment by adamretter** [comment]
> The Saxes parser is parsing whitespace between tags as text nodes

@marmoure Saxes parser may well be correct, it depends on what the whitespace consists of and how the specifications define that it should be handled, see: https://www.w3.org/TR/xml/#sec-white-space
